### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by LoganElliott** [jrwebdev/generator-jrreact#1]
`C:\GitHub> npm i -g generator-jrrreact
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Logan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "generator-jrrreact"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.5
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/generator-jrrreact
npm ERR! 404
npm ERR! 404  'generator-jrrreact' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\npm-debug.log`

Did you forget to push to npm?

**Comment by LoganElliott** [comment]
I lie it does work you just had an extra 'r' in your readme....

**Comment by jrwebdev** [comment]
Cheers @LoganElliott 
There are some issues with the dependencies at the moment - I'm going to make some changes soon and update it to Webpack 2. Might add a TypeScript option too - liking using that in place of `PropTypes`

**Comment by LoganElliott** [comment]
Is the errors with node-sass and eslint I experienced those and ignored them. Oooo Webpack2 nice the first RC is just out https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.0

**Comment by jrwebdev** [comment]
@LoganElliott generator-jrreact v2 is now out! Details in the readme

You might also be interested in https://github.com/jrwebdev/next where I've been trying various things out.

**Comment by LoganElliott** [comment]
Nice, I'll try it out when I get home. Why haven't you got Redux in your 'next' thing? :p

**Comment by jrwebdev** [comment]
Already know how to use it 😄

**Comment by LoganElliott** [comment]
Touché!
